fastlane_version "2.55.0"
default_platform :ios

platform :ios do

  before_all do
    unless ENV["CI"]
      ensure_git_status_clean
    end
  end

  desc "Run all the tests"
  lane :test do
    scan(scheme: "SwiftBeanCount")
  end

  after_all do |lane|
    notification(message: "Fastlane finished '#{lane}'")
  end

end
