name: CI

on:
  pull_request:
    branches:
    - master
  push:
    branches:
    - master

jobs:
  build:
    runs-on: macOS-latest
    steps:
    - name: Select Xcode version
      run: sudo xcode-select -s /Applications/Xcode_11.1.app/
    - uses: actions/checkout@master
    - name: Brew
      run: brew bundle
    - name: Bundle
      run: bundle install
    - name: Fastlane
      run: bundle exec fastlane ci
      env:
          DANGER_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_ACCESS_TOKEN: ${{ secrets.GITHUB_CI_TOKEN }}
